(let ((links
       '(("~/.Xmodmap" . "./x11/.Xmodmap")
         ("~/.inputrc" . "./readline/.inputrc")
         ("~/.mongorc.js" . "./mongodb/.mongorc.js")
         ("~/.tern-project" . "./ternjs/.tern-project")
         ("~/.tmux.conf" . "./tmux/.tmux.conf")
         ("~/.tmux/tmuxline.snapshot" . "./tmux/tmuxline.snapshot")
         ("~/.vimrc" . "./vim/.vimrc")
         ("~/.emacs.d/init.el" . "./emacs/init.el")
         ("~/.emacs.d/myinit.org" . "./emacs/myinit.org"))))
  (dolist (l links 'done)
    (let ((link (expand-file-name (car l)))
	  (target (expand-file-name (cdr l))))
      (when (file-exists-p target)
	(make-symbolic-link target link t)))))
